name: repository-dispatch
description: creates repository_dispatch event in target repository
inputs:
  secret-token:
    description: fine-grained personal access token with content write permission for the target repo
    required: true
  another-secret:
    description: another secret
    required: true
runs:
  using: composite
  steps:
    - # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#masking-a-value-in-a-log
      name: mask secret inputs
      run: |
        echo "::add-mask::${{ inputs.secret-token }}"
        echo "::add-mask::${{ inputs.another-secret }}"
      shell: bash

    - name: test secrets masking
      run: echo "${{ inputs.secret-token }} and ${{ inputs.another-secret }}"
      shell: bash