# This workflow tests the reusable docker-publish workflow

name: test docker-publish

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    # FAIRDataTeam/github-workflows/.github/workflows/docker-publish.yml@main
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    with:
      # https://github.com/docker/build-push-action?tab=readme-ov-file#inputs requires list as newline-delimited string
      build-args: |
        PROJECT_VERSION=1.2.3
      push: ${{ github.event_name != 'pull_request' }}
