# This workflow tests the reusable repo-dispatch action

name: test repo-dispatch action

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout in order to use local action
        uses: actions/checkout@v4
      - name: test action
        uses: ./.github/actions/repo-dispatch
        with:
          secret-token: my-secret-token
          target-repo-name: ${{ github.event.repository.name }}
          target-repo-owner: ${{ github.repository_owner }}
          event-type: my-event
          client-payload: '{"my-key": "my-value"}'
