name: test the receiving end of the repo-dispatch action
# TODO: looks like this is not doing anything here... perhaps not possible in the same repo?

on:
  repository_dispatch:
    types: [my-custom-event-type]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "action: ${{ github.event.action }}"
          echo "payload: ${{ github.event.client_payload.my-key }}"
