# This workflow tests the reusable docker-publish workflow

name: test docker-publish

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    # FAIRDataTeam/github-workflows/.github/workflows/docker-publish.yml@main
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
